#!/usr/bin/env python3
import sys
import os
import re

def parse_recipe(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Match frontmatter between --- and ---
    match = re.match(r'^---\s*\n(.*?)\n---\s*\n(.*)$', content, re.DOTALL)
    if not match:
        raise ValueError(f"No frontmatter found in {file_path}")
    
    frontmatter_str, body = match.groups()
    metadata = {}
    for line in frontmatter_str.splitlines():
        if ':' in line:
            key, val = line.split(':', 1)
            metadata[key.strip()] = val.strip().strip('"').strip("'")
            
    required_keys = ['id', 'title', 'description', 'persona']
    for key in required_keys:
        if key not in metadata:
            raise ValueError(f"Missing key '{key}' in frontmatter of {file_path}")
            
    return {
        'id': metadata['id'],
        'title': metadata['title'],
        'description': metadata['description'],
        'persona': metadata['persona'],
        'content': body.strip()
    }

def main():
    if len(sys.argv) < 4:
        print("Usage: generate_headers.py <output_h> <mcp_instructions_md> <terminal_levels_md> [recipe_md...]")
        sys.exit(1)
        
    out_path = sys.argv[1]
    mcp_path = sys.argv[2]
    term_path = sys.argv[3]
    recipe_paths = sys.argv[4:]
    
    with open(mcp_path, 'r', encoding='utf-8') as f:
        mcp_content = f.read()
        
    with open(term_path, 'r', encoding='utf-8') as f:
        term_content = f.read()
        
    recipes = []
    for path in recipe_paths:
        try:
            recipes.append(parse_recipe(path))
        except Exception as e:
            print(f"Error parsing recipe {path}: {e}", file=sys.stderr)
            sys.exit(1)
            
    # Generate the C++ initializers for recipes
    recipe_initializers = []
    for r in recipes:
        init = (
            f'        {{'
            f'R"id({r["id"]})id", '
            f'R"title({r["title"]})title", '
            f'R"desc({r["description"]})desc", '
            f'R"pers({r["persona"]})pers", '
            f'R"content({r["content"]})content"'
            f'}}'
        )
        recipe_initializers.append(init)
        
    recipe_list_str = ",\n".join(recipe_initializers)
    
    # Generate the header file content
    header_content = f"""// Generated by generate_headers.py. DO NOT EDIT.
#ifndef TERMOBULATOR_INLINED_DOCS_H
#define TERMOBULATOR_INLINED_DOCS_H

#include <string>
#include <vector>

namespace termobulator {{
namespace doc {{

inline std::string GetMcpInstructions() {{
    return R"doc({mcp_content})doc";
}}

inline std::string GetTerminalLevelsDocumentation() {{
    return R"doc({term_content})doc";
}}

struct Recipe {{
    std::string id;
    std::string title;
    std::string description;
    std::string persona;
    std::string content;
}};

inline const std::vector<Recipe>& GetRecipes() {{
    static const std::vector<Recipe> recipes = {{
{recipe_list_str}
    }};
    return recipes;
}}

}} // namespace doc
}} // namespace termobulator

#endif // TERMOBULATOR_INLINED_DOCS_H
"""

    # Create the directory for the output if it doesn't exist
    out_dir = os.path.dirname(out_path)
    if out_dir and not os.path.exists(out_dir):
        os.makedirs(out_dir)

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(header_content)

if __name__ == '__main__':
    main()
